name: Check dependency updates
version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: main
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "IST"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "Dependabot"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
